#!/bin/bash
connectVersion(){
    
    if [ "$1" == "connect" ]; then
        cd ~/automation/marketplace/marketplace-web
        ./auto versin versionmarketplace test
        exit 0
    fi
    
}

deploy(){
    
    if  [ "$1" == "deploy" ]; then
        ssh -t versionaplicativoderestaurante "\
            cd codificar \
            && if [ ! -d "codificar-node" ]; then git clone https://github.com/lucas5g/codificar-node; fi \
            && cd codificar-node \
            && ls -la


        "
        exit 0
    fi
}

push(){
    if [ "$1" == "push" ]; then
        git add .
        git commit -m "$2"
        git push
        ssh -t versionaplicativoderestaurante "\
            cd codificar/codificar-node \
            && git reset --hard \
            && git pull \
            && source ~/.nvm/nvm.sh \
            && nvm use 16 \
            && npm install \
            && pm2 restart codificar-node --update-env  \
        "
    fi
}

command=$1
commit=$2
main(){
    connectVersion $command
    deploy $command
    push $command $commit
    
    
}
main

# connectVersion